basePath: /
host: localhost:8082
info:
  contact:
    email: bitop@spatecon.ru
    name: API Support
    url: https://vk.com/bmstu_schedule
  description: BMSTU dia lab
  license:
    name: AS IS (NO WARRANTY)
  title: BMSTU LAB
  version: "1.0"
paths: {}
schemes:
- http
securityDefinitions:
  BearerAuth:
    description: 'Введите: "Bearer {token}" (без кавычек)'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
